name: Tag kubectl version

on:
  pull_request:
    types: [closed]

jobs:
  tag-kubectl:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check if PR is from renovate and touches Dockerfile
        # if: contains(github.event.pull_request.head.ref, 'renovate') && github.event.pull_request.changed_files > 0
        uses: actions/checkout@main

      - name: Extract kubectl version from PR diff
        id: parse
        run: |
          echo '${{ toJSON(github.event.pull_request) }}'

