name: Renovate

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.3
        with:
          configurationFile: .github/renovate_config.js
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug